### PR TITLE
Add type definitions

### PR DESCRIPTION
**Pull request by tophcodes**
Added Typescript definitions so that this library can more easily be used in Typescript projects

### CODE REVIEW

**Comment by loklaan** [comment]
Hey @padarom thanks for the contrib mate

This looks good, although there are a couple things remaining that I'd love for you to do to get this merged:
1. Add your new def file to [`package.json#types` field](https://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html#including-declarations-in-your-npm-package) so that other project tooling can pick it up without issue
2. Add a way for us to easily validate that the types are correct; I think that the path with least resistance here would be to add a `test/validate.ts` file that uses all of the libraries API surface - running `tsc --noEmit test/validate.ts` should then be part of the main test script for the package.

Does that sound alright?

**Comment by tophcodes** [comment]
Running `tsc` over a validate file will only validate the types within it and not any of the functionality. The only thing we'd be testing by that, by my understanding, is that the `validate.ts` content matches the types from our `index.d.ts`. This doesn't necessarily verify that the `index.d.ts` types at all match the actual interface that is exported by the library.

I think an easier way to do both is to rename the `test/index.js` into `test/index.ts`. We'd properly import the library with its typescript types and keep typescript in unstrict mode. That way we don't need to change anything else in the test. Of course the test would then have to be run with [ts-node](https://github.com/TypeStrong/ts-node).

With this change we're not only testing the type definition of the interface, but also that it matches the actual library and that even with the typing everything still works as expected (i.e. the types don't exclude usage that previously worked).

Is that path okay with you?

**Comment by loklaan** [comment]
@padarom That sounds even better! I'd be stoked to review and merge that in, as part of this PR 👍

**Comment by smenshikov** [comment]
Why this MR is still here? It should be merged

**Comment by loklaan** [comment]
@smenshikov Gday - a pandemic happened. Neither myself or @padarom have checked back in that time.

If you'd like to contribute, to push this PR over the line (in a seperate PR), feel encouraged 👍 

I'd want to see the types _used_ here in the repo, to validate they work. Following the thread, I think the pending tasks would be to
- [ ] Rename `test/index.js` -> `test/index.ts`, & fix any issues
- [ ] Add tsc & some scripts, or just ts-node, to run that test file (this should then validate not only functionality, but also types 👍)

**Comment by loklaan** [comment]
Closing due to inactivity - please open another PR folks if you'd like to push this forward.

**Pull request closed without merging**
