### PR TITLE
Support variable injection in filenames

### PR DESCRIPTION
**Pull request by loklaan**
Giving filename replacement some 💘 .
- [x] Added tests
- [x] Updated docs

### CODE REVIEW

**Comment by loklaan** [comment]
One possible issue, that I didn't tackle, was that if an injection variable doesn't exist, the mustache template part of a filename turns to an empty string... Afaik that is expected. 💃

**Comment by yoshuawuyts** [comment]
LGTM, added you to github and npm as a collaborator :rocket:

**Comment by loklaan** [comment]
Cheers mate. :sparkles: 

I'll get to pushing this stuff later today.

**Comment by yoshuawuyts** [comment]
woot, nice!

**Pull request merged**
